export const levelResultsData = {
  "cpu-scheduling": {
    "fcfs-l1": {
      id: "fcfs-l1",
      title: "FCFS Level 1: Pure FCFS Results",
      module: "Scheduler Dash",
      moduleId: "cpu-scheduling",
      score: 92,
      maxScore: 100,
      xpEarned: 50,
      performance: "Excellent Performance!",
      stars: 3,
      metrics: [
        { label: "Average Waiting Time", value: "5.2s", icon: "Clock", color: "text-cyan-400" },
        { label: "Turnaround Time", value: "12.8s", icon: "TrendingUp", color: "text-green-400" },
        { label: "CPU Utilization", value: "85%", icon: "Cpu", color: "text-blue-400" },
        { label: "Context Switches", value: "8", icon: "RotateCcw", color: "text-orange-400" },
      ],
      analysis: {
        text: "Excellent work! You followed FCFS correctly, maintaining process order and minimizing idle time. Your CPU utilization of 85% shows efficient resource management.",
        comparison: "Compare with Optimal",
      },
      unlocked: {
        level: "FCFS Level 2: Arrival Overlap",
        description: "New level unlocked in Scheduler Dash",
      },
      progressToNext: 66,
    },
    "fcfs-l2": {
      id: "fcfs-l2",
      title: "FCFS Level 2: Arrival Overlap Results",
      module: "Scheduler Dash",
      moduleId: "cpu-scheduling",
      score: 88,
      maxScore: 100,
      xpEarned: 75,
      performance: "Great Job!",
      stars: 3,
      metrics: [
        { label: "Average Waiting Time", value: "6.1s", icon: "Clock", color: "text-cyan-400" },
        { label: "Turnaround Time", value: "13.5s", icon: "TrendingUp", color: "text-green-400" },
        { label: "CPU Utilization", value: "82%", icon: "Cpu", color: "text-blue-400" },
        { label: "Context Switches", value: "10", icon: "RotateCcw", color: "text-orange-400" },
      ],
      analysis: {
        text: "You managed overlapping arrivals well, keeping waiting times low. Try to further optimize context switches.",
        comparison: "Compare with Optimal",
      },
      unlocked: {
        level: "FCFS Level 3: Large Processes",
        description: "New level unlocked in Scheduler Dash",
      },
      progressToNext: 80,
    },
    "fcfs-l3": {
      id: "fcfs-l3",
      title: "FCFS Level 3: Large Processes Results",
      module: "Scheduler Dash",
      moduleId: "cpu-scheduling",
      score: 75,
      maxScore: 100,
      xpEarned: 100,
      performance: "Good Effort!",
      stars: 2,
      metrics: [
        { label: "Average Waiting Time", value: "8.9s", icon: "Clock", color: "text-cyan-400" },
        { label: "Turnaround Time", value: "18.2s", icon: "TrendingUp", color: "text-green-400" },
        { label: "CPU Utilization", value: "78%", icon: "Cpu", color: "text-blue-400" },
        { label: "Context Switches", value: "12", icon: "RotateCcw", color: "text-orange-400" },
      ],
      analysis: {
        text: "Handling large processes is challenging. Focus on reducing waiting time for shorter jobs.",
        comparison: "Compare with Optimal",
      },
      unlocked: {
        level: "SJF Level 1: Equal Arrival",
        description: "Unlocked SJF module",
      },
      progressToNext: 100,
    },
    "sjf-l1": {
      id: "sjf-l1",
      title: "SJF Level 1: Equal Arrival Results",
      module: "Scheduler Dash",
      moduleId: "cpu-scheduling",
      score: 90,
      maxScore: 100,
      xpEarned: 60,
      performance: "Excellent!",
      stars: 3,
      metrics: [
        { label: "Average Waiting Time", value: "4.8s", icon: "Clock", color: "text-cyan-400" },
        { label: "Turnaround Time", value: "11.2s", icon: "TrendingUp", color: "text-green-400" },
        { label: "CPU Utilization", value: "88%", icon: "Cpu", color: "text-blue-400" },
        { label: "Context Switches", value: "7", icon: "RotateCcw", color: "text-orange-400" },
      ],
      analysis: {
        text: "Great use of SJF for equal arrivals. Waiting time is minimized.",
        comparison: "Compare with Optimal",
      },
      unlocked: {
        level: "SJF Level 2: Arrival Spread",
        description: "New level unlocked in SJF",
      },
      progressToNext: 33,
    },
    "sjf-l2": {
      id: "sjf-l2",
      title: "SJF Level 2: Arrival Spread Results",
      module: "Scheduler Dash",
      moduleId: "cpu-scheduling",
      score: 85,
      maxScore: 100,
      xpEarned: 80,
      performance: "Solid Work!",
      stars: 3,
      metrics: [
        { label: "Average Waiting Time", value: "5.5s", icon: "Clock", color: "text-cyan-400" },
        { label: "Turnaround Time", value: "12.7s", icon: "TrendingUp", color: "text-green-400" },
        { label: "CPU Utilization", value: "84%", icon: "Cpu", color: "text-blue-400" },
        { label: "Context Switches", value: "9", icon: "RotateCcw", color: "text-orange-400" },
      ],
      analysis: {
        text: "You handled staggered arrivals well. Try to further reduce context switches.",
        comparison: "Compare with Optimal",
      },
      unlocked: {
        level: "SJF Level 3: Starvation Traps",
        description: "New level unlocked in SJF",
      },
      progressToNext: 66,
    },
    "sjf-l3": {
      id: "sjf-l3",
      title: "SJF Level 3: Starvation Traps Results",
      module: "Scheduler Dash",
      moduleId: "cpu-scheduling",
      score: 70,
      maxScore: 100,
      xpEarned: 120,
      performance: "Needs Improvement",
      stars: 1,
      metrics: [
        { label: "Average Waiting Time", value: "10.2s", icon: "Clock", color: "text-cyan-400" },
        { label: "Turnaround Time", value: "20.1s", icon: "TrendingUp", color: "text-green-400" },
        { label: "CPU Utilization", value: "75%", icon: "Cpu", color: "text-blue-400" },
        { label: "Context Switches", value: "15", icon: "RotateCcw", color: "text-orange-400" },
      ],
      analysis: {
        text: "Starvation occurred for some jobs. Review SJF limitations and consider alternatives.",
        comparison: "Compare with Optimal",
      },
      unlocked: {
        level: "SRTF Level 1: Simple Burst",
        description: "Unlocked SRTF module",
      },
      progressToNext: 100,
    },
    // ...repeat for all other levels in cpu-scheduling...

    "srtf-l1": {
      id: "strf-l1",
      title: "SRTF Level 1: Simple Burst Results",
      module: "Scheduler Dash",
      moduleId: "cpu-scheduling",
      score: 70,
      maxScore: 100,
      xpEarned: 120,
      performance: "Needs Improvement",
      stars: 1,
      metrics: [
          { label: "Average Waiting Time", value: "10.2s", icon: "Clock", color: "text-cyan-400" },
        { label: "Turnaround Time", value: "20.1s", icon: "TrendingUp", color: "text-green-400" },
        { label: "CPU Utilization", value: "75%", icon: "Cpu", color: "text-blue-400" },
        { label: "Context Switches", value: "15", icon: "RotateCcw", color: "text-orange-400" },
      ],
        analysis: {
          text: "You struggled with SRTF's preemption. Focus on managing shorter jobs effectively.",
          comparison: "Compare with Optimal",
        },
        unlocked: {
          level: "SRTF Level 2: Simple Burst",
          description: "Unlocked SRTF module",
        },
        progressToNext: 100,
    },

    "srtf-l2": {
      id: "strf-l1",
      title: "SRTF Level 1: Simple Burst Results",
      module: "Scheduler Dash",
      moduleId: "cpu-scheduling",
      score: 70,
      maxScore: 100,
      xpEarned: 120,
      performance: "Needs Improvement",
      stars: 1,
      metrics: [
          { label: "Average Waiting Time", value: "10.2s", icon: "Clock", color: "text-cyan-400" },
        { label: "Turnaround Time", value: "20.1s", icon: "TrendingUp", color: "text-green-400" },
        { label: "CPU Utilization", value: "75%", icon: "Cpu", color: "text-blue-400" },
        { label: "Context Switches", value: "15", icon: "RotateCcw", color: "text-orange-400" },
      ],
        analysis: {
          text: "You struggled with SRTF's preemption. Focus on managing shorter jobs effectively.",
          comparison: "Compare with Optimal",
        },
        unlocked: {
          level: "SRTF Level 2: Simple Burst",
          description: "Unlocked SRTF module",
        },
        progressToNext: 100,
    },

    "srtf-l3": {
      id: "strf-l1",
      title: "SRTF Level 1: Simple Burst Results",
      module: "Scheduler Dash",
      moduleId: "cpu-scheduling",
      score: 70,
      maxScore: 100,
      xpEarned: 120,
      performance: "Needs Improvement",
      stars: 1,
      metrics: [
          { label: "Average Waiting Time", value: "10.2s", icon: "Clock", color: "text-cyan-400" },
        { label: "Turnaround Time", value: "20.1s", icon: "TrendingUp", color: "text-green-400" },
        { label: "CPU Utilization", value: "75%", icon: "Cpu", color: "text-blue-400" },
        { label: "Context Switches", value: "15", icon: "RotateCcw", color: "text-orange-400" },
      ],
        analysis: {
          text: "You struggled with SRTF's preemption. Focus on managing shorter jobs effectively.",
          comparison: "Compare with Optimal",
        },
        unlocked: {
          level: "SRTF Level 2: Simple Burst",
          description: "Unlocked SRTF module",
        },
        progressToNext: 100,
    },

    "srtf-l4": {
      id: "strf-l1",
      title: "SRTF Level 1: Simple Burst Results",
      module: "Scheduler Dash",
      moduleId: "cpu-scheduling",
      score: 70,
      maxScore: 100,
      xpEarned: 120,
      performance: "Needs Improvement",
      stars: 1,
      metrics: [
          { label: "Average Waiting Time", value: "10.2s", icon: "Clock", color: "text-cyan-400" },
        { label: "Turnaround Time", value: "20.1s", icon: "TrendingUp", color: "text-green-400" },
        { label: "CPU Utilization", value: "75%", icon: "Cpu", color: "text-blue-400" },
        { label: "Context Switches", value: "15", icon: "RotateCcw", color: "text-orange-400" },
      ],
        analysis: {
          text: "You struggled with SRTF's preemption. Focus on managing shorter jobs effectively.",
          comparison: "Compare with Optimal",
        },
        unlocked: {
          level: "Priority Scheduling Level 2: Simple Burst",
          description: "Unlocked SRTF module",
        },
        progressToNext: 100,
    },

    "priority-l1": {
      id: "priority-l1",
      title: "Priority Level 1: Basic Priority Results",
      module: "Scheduler Dash",
      moduleId: "cpu-scheduling",
      score: 80,
      maxScore: 100,
      xpEarned: 150,
      performance: "Good",
      stars: 2,
      metrics: [
        { label: "Average Waiting Time", value: "5.1s", icon: "Clock", color: "text-cyan-400" },
        { label: "Turnaround Time", value: "15.1s", icon: "TrendingUp", color: "text-green-400" },
        { label: "CPU Utilization", value: "80%", icon: "Cpu", color: "text-blue-400" },
        { label: "Context Switches", value: "10", icon: "RotateCcw", color: "text-orange-400" },
      ],
      analysis: {
        text: "You applied priority scheduling effectively. However, some lower-priority processes experienced longer waiting times.",
        comparison: "Compare with Optimal",
      },
      unlocked: {
        level: "Priority Level 2: Dynamic Priorities",
        description: "New level unlocked in Scheduler Dash",
      },
      progressToNext: 80,
    },
    

    "priority-l2": {
      id: "priority-l2",
      title: "Priority Level 2: Dynamic Priorities Results",
      module: "Scheduler Dash",
      moduleId: "cpu-scheduling",
      score: 85,
      maxScore: 100,
      xpEarned: 180,
      performance: "Great!",
      stars: 3,
      metrics: [
        { label: "Average Waiting Time", value: "4.5s", icon: "Clock", color: "text-cyan-400" },
        { label: "Turnaround Time", value: "13.8s", icon: "TrendingUp", color: "text-green-400" },
        { label: "CPU Utilization", value: "82%", icon: "Cpu", color: "text-blue-400" },
        { label: "Context Switches", value: "9", icon: "RotateCcw", color: "text-orange-400" },
      ],
      analysis: {
        text: "Dynamic priorities helped balance load effectively. Keep optimizing for lower waiting times.",
        comparison: "Compare with Optimal",
      },
      unlocked: {
        level: "Priority Level 3: Aging Techniques",
        description: "New level unlocked in Scheduler Dash",
      },
      progressToNext: 66,
    },
    "priority-l3": {
      id: "priority-l3",
      title: "Priority Level 3: Aging Techniques Results",
      module: "Scheduler Dash",
      moduleId: "cpu-scheduling",
      score: 90,
      maxScore: 100,
      xpEarned: 200,
      performance: "Excellent!",
      stars: 3,
      metrics: [
        { label: "Average Waiting Time", value: "3.8s", icon: "Clock", color: "text-cyan-400" },
        { label: "Turnaround Time", value: "12.0s", icon: "TrendingUp", color: "text-green-400" },
        { label: "CPU Utilization", value: "85%", icon: "Cpu", color: "text-blue-400" },
        { label: "Context Switches", value: "8", icon: "RotateCcw", color: "text-orange-400" },
      ],
      analysis: {
        text: "Aging techniques significantly reduced starvation. Your CPU utilization is impressive at 85%.",
        comparison: "Compare with Optimal",
      },
      unlocked: {
        level: "Priority Level 4: Priority Inheritance",
        description: "New level unlocked in Scheduler Dash",
      },
      progressToNext: 50,
    },
    "priority-l4": {
      id: "priority-l4",
      title: "Priority Level 4: Priority Inheritance Results",
      module: "Scheduler Dash",
      moduleId: "cpu-scheduling",
      score: 95,
      maxScore: 100,
      xpEarned: 300,
      performance: "Outstanding!",
      stars: 4,
      metrics: [
        { label: "Average Waiting Time", value: "2.5s", icon: "Clock", color: "text-cyan-400" },
        { label: "Turnaround Time", value: "10.5s", icon: "TrendingUp", color: "text-green-400" },
        { label: "CPU Utilization", value: "92%", icon: "Cpu", color: "text-blue-400" },
        { label: "Context Switches", value: "5", icon: "RotateCcw", color: "text-orange-400" },
      ],
      analysis: {
        text: "Priority inheritance has further reduced waiting times. Your CPU utilization is impressive at 92%.",
        comparison: "Compare with Optimal",
      },
      
      unlocked: {
        level: "Round Robin Level 1: Basic Round Robin",
        description: "Unlocked Round Robin module",
      },
      progressToNext: 100,
    },
    "round-robin-l1": {
      id: "round-robin-l1",
      title: "Round Robin Level 1: Basic Round Robin Results",
      module: "Scheduler Dash",
      moduleId: "cpu-scheduling",
      score: 78,
      maxScore: 100,
      xpEarned: 150,
      performance: "Good",
      stars: 2,
      metrics: [
        { label: "Average Waiting Time", value: "5.5s", icon: "Clock", color: "text-cyan-400" },
        { label: "Turnaround Time", value: "14.0s", icon: "TrendingUp", color: "text-green-400" },
        { label: "CPU Utilization", value: "80%", icon: "Cpu", color: "text-blue-400" },
        { label: "Context Switches", value: "10", icon: "RotateCcw", color: "text-orange-400" },
      ],
      analysis: {
        text: "You applied Round Robin scheduling effectively, but some processes experienced longer waiting times due to time quantum settings.",
        comparison: "Compare with Optimal",
      },
      unlocked: {
        level: "Round Robin Level 2: Time Quantum Optimization",
        description: "New level unlocked in Scheduler Dash",
      },
      progressToNext: 75,
    },
    "round-robin-l2": {
      id: "round-robin-l2",
      title: "Round Robin Level 2: Time Quantum Optimization Results",
      module: "Scheduler Dash",
      moduleId: "cpu-scheduling",
      score: 90,
      maxScore: 100,
      xpEarned: 300,
      performance: "Excellent!",
      stars: 4,
      metrics: [
        { label: "Average Waiting Time", value: "2.7s", icon: "Clock", color: "text-cyan-400" },
        { label: "Turnaround Time", value: "10.5s", icon: "TrendingUp", color: "text-green-400" },
        { label: "CPU Utilization", value: "92%", icon: "Cpu", color: "text-blue-400" },
        { label: "Context Switches", value: "6", icon: "RotateCcw", color: "text-orange-400" },
      ],
      analysis: {
        text: "You optimized Round Robin scheduling by adjusting time quantum settings, achieving better performance metrics.",
        comparison: "Compare with Optimal",
      },
      unlocked: {
        level: "Round Robin Level 3: Complex Workloads",
        description: "New level unlocked in Scheduler Dash",
      },
      progressToNext: 50,
    },
    "round-robin-l3": {
      id: "round-robin-l3",
      title: "Round Robin Level 3: Complex Workloads Results",
      module: "Scheduler Dash",
      moduleId: "cpu-scheduling",
      score: 85,
      maxScore: 100,
      xpEarned: 200,
      performance: "Great Job!",
      stars: 3,
      metrics: [
        { label: "Average Waiting Time", value: "3.5s", icon: "Clock", color: "text-cyan-400" },
        { label: "Turnaround Time", value: "12.0s", icon: "TrendingUp", color: "text-green-400" },
        { label: "CPU Utilization", value: "88%", icon: "Cpu", color: "text-blue-400" },
        { label: "Context Switches", value: "8", icon: "RotateCcw", color: "text-orange-400" },
      ],
      analysis: {
        text: "You handled complex workloads well, maintaining a good balance between waiting time and CPU utilization.",
        comparison: "Compare with Optimal", 
      },
      unlocked: {
        description: "New level unlocked in Scheduler Dash",
      },
      progressToNext: 33,
      }
  },
  
  "memory-management": {
    "first-fit-l1": {
      id: "first-fit-l1",
      title: "First Fit Level 1: Basic Allocation Results",
      module: "Memory Management",
      moduleId: "memory-management",
      score: 82,
      maxScore: 100,
      xpEarned: 100,
      performance: "Good Job!",
      stars: 3,
      metrics: [
        { label: "Memory Utilization", value: "75%", icon: "Memory", color: "text-blue-400" },
        { label: "Fragmentation", value: "15%", icon: "Fragment", color: "text-orange-400" },
        { label: "Allocation Success Rate", value: "85%", icon: "CheckCircle", color: "text-green-400" },
      ],
      analysis: {
        text: "You applied the First Fit algorithm effectively, achieving a good balance between memory utilization and fragmentation. Keep optimizing for better allocation success rates.",
        comparison: "Compare with Optimal",
      },
      unlocked: {
        level: "First Fit Level 2: High Fragmentation",
        description: "New level unlocked in Memory Management",
      },
      progressToNext: 66,
    },
    "first-fit-l2": {
      id: "first-fit-l2",
      title: "First Fit Level 2: High Fragmentation Results",
      module: "Memory Management",
      moduleId: "memory-management",
      score: 78,
      maxScore: 100,
      xpEarned: 120,
      performance: "Good Effort!",
      stars: 2,
      metrics: [
        { label: "Memory Utilization", value: "70%", icon: "Memory", color: "text-blue-400" },
        { label: "Fragmentation", value: "20%", icon: "Fragment", color: "text-orange-400" },
        { label: "Allocation Success Rate", value: "80%", icon: "CheckCircle", color: "text-green-400" },
      ],
      analysis: {
        text: "You managed high fragmentation well, but there is room for improvement in memory utilization and allocation success rates. Consider revisiting your allocation strategy.",
        comparison: "Compare with Optimal",
      },
      unlocked: {
        level: "Best Fit Level 1: Perfect Holes",
        description: "Unlocked Best Fit module",
      },
      progressToNext: 50,
    },
    "best-fit-l1": {
      id: "best-fit-l1",
      title: "Best Fit Level 1: Perfect Holes Results",
      module: "Memory Management",
      moduleId: "memory-management",
      score: 90,
      maxScore: 100,
      xpEarned: 150,
      performance: "Excellent!",
      stars: 4,
      metrics: [
        { label: "Memory Utilization", value: "85%", icon: "Memory", color: "text-blue-400" },
        { label: "Fragmentation", value: "10%", icon: "Fragment", color: "text-orange-400" },
        { label: "Allocation Success Rate", value: "90%", icon: "CheckCircle", color: "text-green-400" },
      ],
      analysis: {
        text: "You applied the Best Fit algorithm effectively, achieving high memory utilization and low fragmentation. Your allocation success rate is impressive.",
        comparison: "Compare with Optimal",
      },
      unlocked: {
        level: "Best Fit Level 2: Hole Minimization",
        description: "New level unlocked in Memory Management",
      },
      progressToNext: 66,
    },
    "best-fit-l2": {
      id: "best-fit-l2",
      title: "Best Fit Level 2: Hole Minimization Results",
      module: "Memory Management",
      moduleId: "memory-management",
      score: 85,
      maxScore: 100,
      xpEarned: 100,
      performance: "Good Effort!",
      stars: 2,
      metrics: [
        { label: "Memory Utilization", value: "75%", icon: "Memory", color: "text-blue-400" },
        { label: "Fragmentation", value: "15%", icon: "Fragment", color: "text-orange-400" },
        { label: "Allocation Success Rate", value: "85%", icon: "CheckCircle", color: "text-green-400" },
      ],
      analysis: {
        text: "You managed hole minimization well, but there is room for improvement in memory utilization and fragmentation. Consider revisiting your allocation strategy.",
        comparison: "Compare with Optimal",
      },
      unlocked: {
        level: "Worst Fit Level 1: Blast Match",
        description: "Unlocked Worst Fit module",
      },
      progressToNext: 50,
    },
    "worst-fit-l1": {
      id: "worst-fit-l1",
      title: "Worst Fit Level 1: Blast Match Results",
      module: "Memory Management",
      moduleId: "memory-management",
      score: 80,
      maxScore: 100,
      xpEarned: 120,
      performance: "Good Job!",
      stars: 3,
      metrics: [
        { label: "Memory Utilization", value: "80%", icon: "Memory", color: "text-blue-400" },
        { label: "Fragmentation", value: "12%", icon: "Fragment", color: "text-orange-400" },
        { label: "Allocation Success Rate", value: "88%", icon: "CheckCircle", color: "text-green-400" },
      ],
      analysis: {
        text: "You applied the Worst Fit algorithm effectively, achieving a good balance between memory utilization and fragmentation. Keep optimizing for better allocation success rates.",
        comparison: "Compare with Optimal",
      },
      unlocked: {
        level: "Worst Fit Level 2: Fragmentation Evolution",
        description: "New level unlocked in Memory Management",
      },
      progressToNext: 66,
    },
    "worst-fit-l2": {
      id: "worst-fit-l2",
      title: "Worst Fit Level 2: Fragmentation Evolution Results",
      module: "Memory Management",
      moduleId: "memory-management",
      score: 75,
      maxScore: 100,
      xpEarned: 100,
      performance: "Needs Improvement",
      stars: 2,
      metrics: [
        { label: "Memory Utilization", value: "70%", icon: "Memory", color: "text-blue-400" },
        { label: "Fragmentation", value: "18%", icon: "Fragment", color: "text-orange-400" },
        { label: "Allocation Success Rate", value: "80%", icon: "CheckCircle", color: "text-green-400" },
      ],
      analysis: {
        text: "You struggled with the Worst Fit algorithm, leading to higher fragmentation and lower memory utilization. Focus on improving your allocation strategy.",
        comparison: "Compare with Optimal",
      },
      unlocked: {
        level: "Paging Level 1: Simple Load Pages",
        description: "Unlocked Paging module",
      },
      progressToNext: 50,
    },
    "paging-l1": {
      id: "paging-l1",
      title: "Paging Level 1: Simple Load Pages Results",
      module: "Memory Management",
      moduleId: "memory-management",
      score: 65,
      maxScore: 100,
      xpEarned: 80,
      performance: "Needs Improvement",
      stars: 2,
      metrics: [
        { label: "Memory Utilization", value: "40%", icon: "Memory", color: "text-blue-400" },
        { label: "Fragmentation", value:  "30%", icon: "Fragment", color: "text-orange-400" },
        { label: "Page Fault Rate", value: "25%", icon: "AlertTriangle", color: "text-red-400" },
      ],
      analysis: {
        text: "You applied paging but faced high fragmentation and page fault rates. Focus on optimizing page sizes and allocation strategies.",
        comparison: "Compare with Optimal",
      },
      unlocked: {
        level: "Paging Level 2: Page Faults",
        description: "New level unlocked in Memory Management",
      },
      progressToNext: 66,
    },
    "paging-l2": {
      id: "paging-l2",
      title: "Paging Level 2: Page Faults Results",
      module: "Memory Management",
      moduleId: "memory-management",
      score: 70,
      maxScore: 100,
      xpEarned: 100,
      performance: "Needs Improvement",
      stars: 2,
      metrics: [
        { label: "Memory Utilization", value: "50%", icon: "Memory", color: "text-blue-400" },
        { label: "Fragmentation", value: "25%", icon: "Fragment", color: "text-orange-400" },
        { label: "Page Fault Rate", value: "20%", icon: "AlertTriangle", color: "text-red-400" },
      ],
      analysis: {
        text: "You improved memory utilization but still faced high fragmentation and page fault rates. Consider optimizing your page replacement algorithms.",
        comparison: "Compare with Optimal",
      },
      unlocked: {
        level: "Paging Level 3: Page Table Mapping",
        description: "New level unlocked in Memory Management",
      },
      progressToNext: 50,
    },  
    "paging-l3": {  
      id: "paging-l3",
      title: "Paging Level 3: Page Table Mapping Results",
      module: "Memory Management",
      moduleId: "memory-management",
      score: 80,
      maxScore: 100,
      xpEarned: 120,
      performance: "Good",
      stars: 3,
      metrics: [
        { label: "Memory Utilization", value: "60%", icon: "Memory", color: "text-blue-400" },
        { label: "Fragmentation", value: "20%", icon: "Fragment", color: "text-orange-400" },
        { label: "Page Fault Rate", value: "15%", icon: "AlertTriangle", color: "text-red-400" },
        { label: "Page Table Size", value: "512KB", icon: "FileText", color: "text-purple-400" },
      ],
      analysis: {
        text: "You effectively managed page table mapping, achieving better memory utilization and lower fragmentation. Your page fault rate is also improving.",
        comparison: "Compare with Optimal",
      },
      unlocked: {
        level: "Segmentation Level 1: Basic Segments Loading",
        description: "Unlocked Segmentation module",
      },
      progressToNext: 66,
    },
    "segmentation-l1": {
      id: "segmentation-l1",
      title: "Segmentation Level 1: Basic Segments Loading Results",
      module: "Memory Management",
      moduleId: "memory-management",
      score: 75,
      maxScore: 100,
      xpEarned: 100,
      performance: "Good Effort!",
      stars: 2,
      metrics: [
        { label: "Memory Utilization", value: "70%", icon: "Memory", color: "text-blue-400" },
        { label: "Fragmentation", value: "15%", icon: "Fragment", color: "text-orange-400" },
        { label: "Page Fault Rate", value: "10%", icon: "AlertTriangle", color: "text-red-400" },
        { label: "Page Table Size", value: "1MB", icon: "FileText", color: "text-purple-400" },
      ],
      analysis: {
        text: "You managed to load segments efficiently, but there is room for improvement in memory utilization and page fault rates.",
        comparison: "Compare with Optimal",
      },
      unlocked: {
        level: "Segmentation Level 2: Overlapping and Gaps",
        description: "New level unlocked in Memory Management",
      },
      progressToNext: 66,
    },
    "segmentation-l2": {  
      id: "segmentation-l2",
      title: "Segmentation Level 2: Overlapping and Gaps",
      module: "Memory Management",
      moduleId: "memory-management",
      score: 80,
      maxScore: 100,
      xpEarned: 120,
      performance: "Good Effort!",
      stars: 2,
      metrics: [
        { label: "Memory Utilization", value: "80%", icon: "Memory", color: "text-blue-400" },
        { label: "Fragmentation", value: "10%", icon: "Fragment", color: "text-orange-400" },
        { label: "Page Fault Rate", value: "5%", icon: "AlertTriangle", color: "text-red-400" },
        { label: "Page Table Size", value: "512KB", icon: "FileText", color: "text-purple-400" },
      ],
      analysis: {
        text: "You effectively managed overlapping segments and gaps, achieving good memory utilization and low fragmentation. Your page fault rate is also improving.",
        comparison: "Compare with Optimal",
      },
      unlocked: {
        level: "Fragmentation and Compaction Level 1: Fragmntation Metrics",
        description: "Unlocked Fragmentation and Compaction module",
      },
      progressToNext: 50,
    },
    "fragmentation-compaction-l1": {
      id: "fragmentation-compaction-l1",
      title: "Fragmentation and Compaction Level 1: Fragmentation Metrics Results",
      module: "Memory Management",
      moduleId: "memory-management",
      score: 70,
      maxScore: 100,
      xpEarned: 80,
      performance: "Needs Improvement",
      stars: 2,
      metrics: [
        { label: "Memory Utilization", value: "60%", icon: "Memory", color: "text-blue-400" },
        { label: "Fragmentation", value: "20%", icon: "Fragment", color: "text-orange-400" },
        { label: "Compaction Time", value: "15s", icon: "Clock", color: "text-cyan-400" },
        { label: "Compaction Success Rate", value: "70%", icon: "CheckCircle", color: "text-green-400" },
      ],
      analysis: {
        text: "Your memory utilization is satisfactory, but you can improve fragmentation and compaction efficiency.",
        comparison: "Compare with Optimal",
      },
      unlocked: {
        level: "Fragmentation and Compaction Level 2: Compaction Logic",
        description: "New level unlocked in Fragmentation and Compaction module",
      },
      progressToNext: 40,
    },
    "fragmentation-compaction-l2": {
      id: "fragmentation-compaction-l2",
      title: "Fragmentation and Compaction Level 2: Compaction Logic Results",
      module: "Memory Management",
      moduleId: "memory-management",
      score: 90,
      maxScore: 100,
      xpEarned: 120,
      performance: "Excellent!",
      stars: 4,
      metrics: [
        { label: "Memory Utilization", value: "85%", icon: "Memory", color: "text-blue-400" },
        { label: "Fragmentation", value: "5%", icon: "Fragment", color: "text-orange-400" },
        { label: "Compaction Time", value: "10s", icon: "Clock", color: "text-cyan-400" },
        { label: "Compaction Success Rate", value: "90%", icon: "CheckCircle", color: "text-green-400" },
      ],
      analysis: {
        text: "You implemented compaction logic effectively, achieving high memory utilization and low fragmentation. Your compaction time and success rate are also impressive.",
        comparison: "Compare with Optimal",
      },
      unlocked: {
        description: "New level unlocked in Fragmentation and Compaction module",
      },
      progressToNext: 60,
    }
  },
  "process-synchronization": {
    "critical-section-l1": {
      id: "critical-section-l1",
      title: "Critical Section Level 1: Two Threads",
      module: "Process Synchronization",
      moduleId: "process-synchronization",
      score: 90,
      maxScore: 100,
      xpEarned: 50,
      performance: "Excellent Performance!",
      stars: 3,
      metrics: [
        { label: "Lock Acquisitions", value: "10", icon: "Lock", color: "text-blue-400" },
        { label: "Lock Releases", value: "5", icon: "LockOpen", color: "text-orange-400" },
        { label: "Lock Contention", value: "0", icon: "Lock", color: "text-green-400" },
      ],
      analysis: {
        text: "You successfully implemented a critical section for two threads without contention. Great job!",
        comparison: "Compare with Optimal",
      },
      unlocked: {
        level: "Critical Section Level 2: Two Threads Shared Paths",
        description: "New level unlocked in Process Synchronization module",
      },
      progressToNext: 60,
    },
    "critical-section-l2": {
      id: "critical-section-l2",
      title: "Critical Section Level 2: Two Threads Shared Paths Results",
      module: "Process Synchronization",
      moduleId: "process-synchronization",
      score: 85,
      maxScore: 100,
      xpEarned: 70,
      performance: "Good Job!",
      stars: 2,
      metrics: [
        { label: "Lock Acquisitions", value: "15", icon: "Lock", color: "text-blue-400" },
        { label: "Lock Releases", value: "10", icon: "LockOpen", color: "text-orange-400" },
        { label: "Lock Contention", value: "5", icon: "Lock", color: "text-red-400" },
      ],
      analysis: {
        text: "You implemented a critical section with shared paths, but there is contention. Consider implementing a more efficient synchronization mechanism.",
        comparison: "Compare with Optimal",
      },
      unlocked: {
        level: "Mutex Level 1: Simple Lock",
        description: "Unlocked Mutex module",
      },
      progressToNext: 50,
    },
    "mutex-l1": {
      id: "mutex-l1",
      title: "Mutex Level 1: Simple Lock Results",
      module: "Process Synchronization",
      moduleId: "process-synchronization",
      score: 80,
      maxScore: 100,
      xpEarned: 60,
      performance: "Good Effort!",
      stars: 2,
      metrics: [
        { label: "Lock Acquisitions", value: "20", icon: "Lock", color: "text-blue-400" },
        { label: "Lock Releases", value: "15", icon: "LockOpen", color: "text-orange-400" },
        { label: "Lock Contention", value: "3", icon: "Lock", color: "text-green-400" },
      ],
      analysis: {
        text: "You implemented a simple mutex lock effectively, achieving low contention. Keep up the good work!",
        comparison: "Compare with Optimal",
      },
      unlocked: {
        level: "Mutex Level 2: Multi-Threaded Locks",
        description: "Unlocked Mutex module",
      },
      progressToNext: 66,
    },
    "mutex-l2": {
      id: "mutex-l2",
      title: "Mutex Level 2: Multi-Threaded Locks Results",
      module: "Process Synchronization",
      moduleId: "process-synchronization",
      score: 85,
      maxScore: 100,
      xpEarned: 70,
      performance: "Good Job!",
      stars: 2,
      metrics: [
        { label: "Lock Acquisitions", value: "25", icon: "Lock", color: "text-blue-400" },
        { label: "Lock Releases", value: "20", icon: "LockOpen", color: "text-orange-400" },
        { label: "Lock Contention", value: "2", icon: "Lock", color: "text-green-400" },
      ],
      analysis: {
        text: "You implemented multi-threaded locks effectively, achieving low contention. Your lock acquisition and release metrics are also improving.",
        comparison: "Compare with Optimal",
      },
      unlocked: {
        level: "Binary Semaphore Level 1: Simple Wait-Signal",
        description: "Unlocked Binary Semaphore module",
      },
      progressToNext: 50,
    },
    "binary-semaphore-l1": {
      id: "binary-semaphore-l1",
      title: "Binary Semaphore Level 1: Simple Wait-Signal Results",
      module: "Process Synchronization",
      moduleId: "process-synchronization",
      score: 75,
      maxScore: 100,
      xpEarned: 50,
      performance: "Good Effort!",
      stars: 2,
      metrics: [
        { label: "Wait Operations", value: "30", icon: "PauseCircle", color: "text-blue-400" },
        { label: "Signal Operations", value: "25", icon: "PlayCircle", color: "text-orange-400" },
        { label: "Contention", value: "5", icon: "AlertTriangle", color: "text-red-400" },
      ],
      analysis: {
        text: "You implemented a simple binary semaphore correctly, but there is room for improvement in contention. Keep up the good work!",
        comparison: "Compare with Optimal",
      },
      unlocked: {
        level: "Binary Semaphore Level 2: Pre-Loaded Queues",
        description: "Unlocked Semaphore module",
      },
      progressToNext: 50,
    },
    "binary-semaphore-l2": {
      id: "binary-semaphore-l2",
      title: "Binary Semaphore Level 2: Pre-Loaded Queues Results",
      module: "Process Synchronization",
      moduleId: "process-synchronization",
      score: 80,
      maxScore: 100,
      xpEarned: 60,
      performance: "Good Job!",
      stars: 3,
      metrics: [
        { label: "Wait Operations", value: "35", icon: "PauseCircle", color: "text-blue-400" },
        { label: "Signal Operations", value: "30", icon: "PlayCircle", color: "text-orange-400" },
        { label: "Contention", value: "3", icon: "AlertTriangle", color: "text-green-400" },
      ],
      analysis: {
        text: "You effectively managed pre-loaded queues with binary semaphores, achieving low contention. Your wait and signal operations are also improving.",
        comparison: "Compare with Optimal",
      },
      unlocked: {
        level: "Counting Semaphore Level 1: Parking Lot Scenario",
        description: "Unlocked Semaphore module",
      },
      progressToNext: 66,
    },
    "counting-semaphore-l1": {
      id: "counting-semaphore-l1",
      title: "Counting Semaphore Level 1: Parking Lot Scenario Results",
      module: "Process Synchronization",
      moduleId: "process-synchronization",
      score: 85,
      maxScore: 100,
      xpEarned: 70,
      performance: "Great Job!",
      stars: 4,
      metrics: [
        { label: "Wait Operations", value: "40", icon: "PauseCircle", color: "text-blue-400" },
        { label: "Signal Operations", value: "35", icon: "PlayCircle", color: "text-orange-400" },
        { label: "Contention", value: "2", icon: "AlertTriangle", color: "text-green-400" },
      ],
      analysis: {
        text: "You implemented counting semaphores effectively in the parking lot scenario. Your wait and signal operations are improving, and you have low contention.",
        comparison: "Compare with Optimal",
      },
      unlocked: {
        level: "Counting Semaphore Level 2: Resource Topology Scenario",
        description: "Unlocked Semaphore module",
      },
      progressToNext: 50,
    },
    "counting-semaphore-l2": {
      id: "counting-semaphore-l2",
      title: "Counting Semaphore Level 2: Resource Topology Results",
      module: "Process Synchronization",
      moduleId: "process-synchronization",
      score: 80,
      maxScore: 100,
      xpEarned: 60,
      performance: "Good Job!",
      stars: 3,
      metrics: [
        { label: "Wait Operations", value: "35", icon: "PauseCircle", color: "text-blue-400" },
        { label: "Signal Operations", value: "30", icon: "PlayCircle", color: "text-orange-400" },
        { label: "Contention", value: "4", icon: "AlertTriangle", color: "text-red-400" },
      ],
      analysis: {
        text: "You effectively managed resource topology with counting semaphores, but there is room for improvement in contention. Keep up the good work!",
        comparison: "Compare with Optimal",
      },
      unlocked: {
        level: "Producer-Consumer Level 1: One Producer-Consumer",
        description: "Unlocked Producer-Consumer module",
      },
      progressToNext: 30,
    },
    "producer-consumer-l1": {
      id: "producer-consumer-l1",
      title: "Producer-Consumer Level 1: One Producer-Consumer Results",
      module: "Process Synchronization",
      moduleId: "process-synchronization",
      score: 90,
      maxScore: 100,
      xpEarned: 80,
      performance: "Excellent!",
      stars: 4,
      metrics: [
        { label: "Produced Items", value: "50", icon: "Package", color: "text-blue-400" },
        { label: "Consumed Items", value: "50", icon: "ShoppingCart", color: "text-orange-400" },
        { label: "Buffer Size", value: "10", icon: "Box", color: "text-green-400" },
        { label: "Wait Time", value: "2s", icon: "Clock", color: "text-cyan-400" },
      ],
      analysis: {
        text: "You successfully implemented a producer-consumer scenario with one producer and one consumer. Great job!",
        comparison: "Compare with Optimal",
      },
      unlocked: {
        level: "Producer-Consumer Level 2: Multiple Producers and Consumers",
        description: "New level unlocked in Process Synchronization module",
      },
      progressToNext: 66,
    },
    "producer-consumer-l2": {
      id: "producer-consumer-l2",
      title: "Producer-Consumer Level 2: Multiple Producers and Consumers Results",
      module: "Process Synchronization",
      moduleId: "process-synchronization",
      score: 85,
      maxScore: 100,
      xpEarned: 70,
      performance: "Good Job!",
      stars: 3,
      metrics: [
        { label: "Produced Items", value: "100", icon: "Package", color: "text-blue-400" },
        { label: "Consumed Items", value: "95", icon: "ShoppingCart", color: "text-orange-400" },
        { label: "Buffer Size", value: "20", icon: "Box", color: "text-green-400" },
        { label: "Wait Time", value: "3s", icon: "Clock", color: "text-cyan-400" },
      ],
      analysis: {
        text: "You effectively managed multiple producers and consumers, achieving a good balance between production and consumption. Your buffer size and wait time are also improving.",
        comparison: "Compare with Optimal",
      },
      unlocked: {
        level: "Producer-Consumer Level 3: Buffer Overflow",
        description: "New level unlocked in Process Synchronization module",
      },
      progressToNext: 66,
    },

    "producer-consumer-l3": {
      id: "producer-consumer-l3",
      title: "Producer-Consumer Level 3: Buffer Overflow Results",
      module: "Process Synchronization",
      moduleId: "process-synchronization",
      score: 80,
      maxScore: 100,
      xpEarned: 60,
      performance: "Good Effort!",
      stars: 2,
      metrics: [
        { label: "Produced Items", value: "120", icon: "Package", color: "text-blue-400" },
        { label: "Consumed Items", value: "100", icon: "ShoppingCart", color: "text-orange-400" },
        { label: "Buffer Size", value: "30", icon: "Box", color: "text-green-400" },
        { label: "Wait Time", value: "5s", icon: "Clock", color: "text-cyan-400" },
      ],
      analysis: {
        text: "You managed buffer overflow effectively, but there is room for improvement in production and consumption rates. Consider optimizing your buffer size and wait time.",
        comparison: "Compare with Optimal",
      },
      unlocked: {
        level: "Dining-Philosophers Level 1: Circular Deadlock",
        description: "New level unlocked in Process Synchronization module",
      },
      progressToNext: 50,
    },
    "dining-philosophers-l1": {
      id: "dining-philosophers-l1",
      title: "Dining Philosophers Level 1: Circular Deadlock Results",
      module: "Process Synchronization",
      moduleId: "process-synchronization",
      score: 70,
      maxScore: 100,
      xpEarned: 50,
      performance: "Needs Improvement",
      stars: 2,
      metrics: [
        { label: "Philosophers Starved", value: "3", icon: "AlertTriangle", color: "text-red-400" },
        { label: "Forks Acquired", value: "5", icon: "ForkKnife", color: "text-blue-400" },
        { label: "Deadlocks Occurred", value: "2", icon: "XCircle", color: "text-orange-400" },
      ],
      analysis: {
        text: "You encountered a circular deadlock in the dining philosophers problem. Consider implementing a solution to prevent deadlocks.",
        comparison: "Compare with Optimal",
      },
      unlocked: {
        level: "Dining Philosophers Level 2: Philospohers Duty",
        description: "New level unlocked in Process Synchronization module",
      },
      progressToNext: 66,
    },
    "dining-philosophers-l2": {
      id: "dining-philosophers-l2",
      title: "Dining Philosophers Level 2: Philosophers Duty Results",
      module: "Process Synchronization",
      moduleId: "process-synchronization",
      score: 75,
      maxScore: 100,
      xpEarned: 60,
      performance: "Good Effort!",
      stars: 2,
      metrics: [
        { label: "Philosophers Starved", value: "2", icon: "AlertTriangle", color: "text-red-400" },
        { label: "Forks Acquired", value: "8", icon: "ForkKnife", color: "text-blue-400" },
        { label: "Deadlocks Occurred", value: "1", icon: "XCircle", color: "text-orange-400" },
      ],
      analysis: {
        text: "You managed to reduce starvation and deadlocks in the dining philosophers problem, but there is still room for improvement. Consider implementing a more efficient solution.",
        comparison: "Compare with Optimal",
      },
      unlocked: {
        description: "New level unlocked in Process Synchronization module"
      },
      progressToNext: 80,
    }
  }
  // ...repeat for memory-management and process-synchronization modules...
} as const; 