// Data structure for mini-quest quizzes, organized by moduleId and miniQuestOverviewId
// Each quiz contains a title, timeLimit, and an array of questions
// Each question contains id, question, options, correctAnswer, explanation, difficulty, and concept

export const miniQuestQuizData = {
  "cpu-scheduling": {
    "fcfs": {
      title: "FCFS Mini-Quest Quiz",
      timeLimit: 600,
      questions: [
        {
          id: 1,
          question: "Which CPU scheduling algorithm is non-preemptive and processes jobs in the order they arrive?",
          options: ["Round Robin", "First-Come, First-Served (FCFS)", "Shortest Job First (SJF)", "Priority Scheduling"],
          correctAnswer: 1,
          explanation: "FCFS is a non-preemptive algorithm that processes jobs in the order they arrive in the ready queue.",
          difficulty: "Easy",
          concept: "Basic Scheduling",
        },
        {
          id: 2,
          question: "In FCFS scheduling, what is the main disadvantage?",
          options: ["Starvation", "Convoy Effect", "High Throughput", "Low Turnaround Time"],
          correctAnswer: 1,
          explanation: "FCFS can lead to the convoy effect, where short processes wait for one long process to complete.",
          difficulty: "Medium",
          concept: "Scheduling Issues",
        },
        {
          id: 3,
          question: "What happens when a long process arrives first in FCFS?",
          options: ["It gets preempted", "All other processes must wait", "It gets lowest priority", "It runs in parallel"],
          correctAnswer: 1,
          explanation: "In FCFS, if a long process arrives first, all subsequent processes must wait, causing the convoy effect.",
          difficulty: "Easy",
          concept: "Convoy Effect",
        },
        {
          id: 4,
          question: "Is FCFS optimal in terms of average waiting time?",
          options: ["Yes, always", "No, never", "Only for equal burst times", "Only for sorted processes"],
          correctAnswer: 1,
          explanation: "FCFS is generally not optimal for average waiting time as it doesn't consider process burst times.",
          difficulty: "Medium",
          concept: "Performance",
        },
        {
          id: 5,
          question: "Can FCFS cause starvation?",
          options: ["Yes, frequently", "No, never", "Only with priority", "Only in preemptive mode"],
          correctAnswer: 1,
          explanation: "FCFS cannot cause starvation as every process will eventually get CPU time in arrival order.",
          difficulty: "Medium",
          concept: "Starvation",
        },
        {
          id: 6,
          question: "What is the time complexity of FCFS scheduling?",
          options: ["O(1)", "O(n)", "O(n log n)", "O(n²)"],
          correctAnswer: 0,
          explanation: "FCFS has O(1) time complexity as it simply picks the first process in the queue.",
          difficulty: "Hard",
          concept: "Complexity",
        },
        {
          id: 7,
          question: "In FCFS, when does context switching occur?",
          options: ["Every time quantum", "Only when process completes", "When higher priority arrives", "Randomly"],
          correctAnswer: 1,
          explanation: "FCFS is non-preemptive, so context switching only occurs when the current process completes or blocks.",
          difficulty: "Medium",
          concept: "Context Switching",
        },
        {
          id: 8,
          question: "Which metric is FCFS worst at optimizing?",
          options: ["Throughput", "Average waiting time", "CPU utilization", "Response time"],
          correctAnswer: 1,
          explanation: "FCFS typically has poor average waiting time, especially when long processes arrive before short ones.",
          difficulty: "Medium",
          concept: "Performance Metrics",
        },
        {
          id: 9,
          question: "Is FCFS suitable for time-sharing systems?",
          options: ["Yes, ideal", "No, not suitable", "Only for batch systems", "Only with modifications"],
          correctAnswer: 1,
          explanation: "FCFS is not suitable for time-sharing systems as it doesn't provide good response time for interactive processes.",
          difficulty: "Hard",
          concept: "System Suitability",
        },
        {
          id: 10,
          question: "What data structure is typically used to implement FCFS?",
          options: ["Stack", "Queue", "Priority Queue", "Binary Tree"],
          correctAnswer: 1,
          explanation: "FCFS uses a FIFO queue to maintain the order of process arrival.",
          difficulty: "Easy",
          concept: "Implementation",
        },
      ],
    },
    "sjf": {
      title: "SJF Mini-Quest Quiz",
      timeLimit: 600,
      questions: [
        {
          id: 1,
          question: "What does SJF stand for?",
          options: ["Shortest Job First", "System Job First", "Sequential Job Flow", "Simple Job Format"],
          correctAnswer: 0,
          explanation: "SJF stands for Shortest Job First, a scheduling algorithm that selects the process with the smallest burst time.",
          difficulty: "Easy",
          concept: "SJF Basics",
        },
        {
          id: 2,
          question: "Is SJF preemptive or non-preemptive?",
          options: ["Always preemptive", "Always non-preemptive", "Can be both", "Neither"],
          correctAnswer: 2,
          explanation: "SJF can be implemented as both non-preemptive (SJF) and preemptive (SRTF - Shortest Remaining Time First).",
          difficulty: "Medium",
          concept: "Preemption",
        },
        {
          id: 3,
          question: "What is the main advantage of SJF?",
          options: ["Easy implementation", "Minimum average waiting time", "No starvation", "Fair to all processes"],
          correctAnswer: 1,
          explanation: "SJF provides the minimum average waiting time among all scheduling algorithms.",
          difficulty: "Easy",
          concept: "Advantages",
        },
        {
          id: 4,
          question: "What is the main disadvantage of SJF?",
          options: ["High overhead", "Convoy effect", "Starvation of long processes", "Low throughput"],
          correctAnswer: 2,
          explanation: "SJF can cause starvation of longer processes if shorter processes keep arriving.",
          difficulty: "Medium",
          concept: "Disadvantages",
        },
        {
          id: 5,
          question: "What information does SJF require to work optimally?",
          options: ["Process priority", "CPU burst time", "Arrival time only", "Memory requirements"],
          correctAnswer: 1,
          explanation: "SJF requires knowledge of CPU burst time to select the shortest job.",
          difficulty: "Easy",
          concept: "Requirements",
        },
        {
          id: 6,
          question: "Is it always possible to know the exact burst time in advance?",
          options: ["Yes, always", "No, must be predicted", "Only for batch systems", "Only for real-time systems"],
          correctAnswer: 1,
          explanation: "Burst time is usually not known in advance and must be predicted using techniques like exponential averaging.",
          difficulty: "Hard",
          concept: "Prediction",
        },
        {
          id: 7,
          question: "Which algorithm is the preemptive version of SJF?",
          options: ["FCFS", "Round Robin", "SRTF", "Priority Scheduling"],
          correctAnswer: 2,
          explanation: "SRTF (Shortest Remaining Time First) is the preemptive version of SJF.",
          difficulty: "Medium",
          concept: "Variants",
        },
        {
          id: 8,
          question: "In SJF, what happens when two processes have the same burst time?",
          options: ["Random selection", "FCFS is used", "Higher priority wins", "Both run in parallel"],
          correctAnswer: 1,
          explanation: "When burst times are equal, FCFS (First-Come, First-Served) is typically used as a tiebreaker.",
          difficulty: "Medium",
          concept: "Tie Breaking",
        },
        {
          id: 9,
          question: "Is SJF optimal for minimizing average waiting time?",
          options: ["Yes, provably optimal", "No, suboptimal", "Only for batch systems", "Only without I/O"],
          correctAnswer: 0,
          explanation: "SJF is provably optimal for minimizing average waiting time when all processes are available simultaneously.",
          difficulty: "Hard",
          concept: "Optimality",
        },
        {
          id: 10,
          question: "What technique is commonly used to estimate burst time?",
          options: ["Random guess", "Exponential averaging", "Linear regression", "Fixed value"],
          correctAnswer: 1,
          explanation: "Exponential averaging is commonly used to predict the next CPU burst based on previous bursts.",
          difficulty: "Hard",
          concept: "Estimation",
        },
      ],
    },
    "srtf": {
      title: "SRTF Mini-Quest Quiz",
      timeLimit: 720,
      questions: [
        {
          id: 1,
          question: "What does SRTF stand for?",
          options: ["Shortest Remaining Time First", "System Resource Time First", "Sequential Round Time First", "Simple Real-Time First"],
          correctAnswer: 0,
          explanation: "SRTF stands for Shortest Remaining Time First, the preemptive version of SJF.",
          difficulty: "Easy",
          concept: "SRTF Basics",
        },
        {
          id: 2,
          question: "Is SRTF preemptive or non-preemptive?",
          options: ["Non-preemptive", "Preemptive", "Both", "Neither"],
          correctAnswer: 1,
          explanation: "SRTF is a preemptive algorithm that can interrupt a running process if a new process with shorter remaining time arrives.",
          difficulty: "Easy",
          concept: "Preemption",
        },
        {
          id: 3,
          question: "What is the main disadvantage of SRTF?",
          options: ["Low throughput", "High context switching overhead", "Poor CPU utilization", "Convoy effect"],
          correctAnswer: 1,
          explanation: "SRTF can lead to high context switching overhead due to frequent preemption.",
          difficulty: "Medium",
          concept: "Disadvantages",
        },
        {
          id: 4,
          question: "When does SRTF preempt the currently running process?",
          options: ["Every time quantum", "When a shorter process arrives", "Randomly", "Never"],
          correctAnswer: 1,
          explanation: "SRTF preempts when a new process arrives with remaining time shorter than the current process.",
          difficulty: "Easy",
          concept: "Preemption Logic",
        },
        {
          id: 5,
          question: "Can SRTF cause starvation?",
          options: ["No, never", "Yes, for long processes", "Only in batch systems", "Only with equal priorities"],
          correctAnswer: 1,
          explanation: "SRTF can cause starvation of longer processes if shorter processes continuously arrive.",
          difficulty: "Medium",
          concept: "Starvation",
        },
        {
          id: 6,
          question: "What metric does SRTF optimize?",
          options: ["Throughput", "Average waiting time", "CPU utilization", "Response time"],
          correctAnswer: 1,
          explanation: "SRTF optimizes average waiting time by always running the process with the shortest remaining time.",
          difficulty: "Medium",
          concept: "Optimization",
        },
        {
          id: 7,
          question: "Compared to SJF, SRTF has:",
          options: ["Lower average waiting time", "Higher average waiting time", "Same waiting time", "No relation"],
          correctAnswer: 0,
          explanation: "SRTF generally has lower or equal average waiting time compared to non-preemptive SJF.",
          difficulty: "Hard",
          concept: "Comparison",
        },
        {
          id: 8,
          question: "What information must be tracked for each process in SRTF?",
          options: ["Priority only", "Remaining burst time", "Arrival time only", "Memory size"],
          correctAnswer: 1,
          explanation: "SRTF must track the remaining burst time for each process to make scheduling decisions.",
          difficulty: "Medium",
          concept: "Implementation",
        },
        {
          id: 9,
          question: "Is SRTF practical for real-world systems?",
          options: ["Yes, widely used", "No, too much overhead", "Only for embedded systems", "Only for supercomputers"],
          correctAnswer: 1,
          explanation: "SRTF is often impractical due to high context switching overhead and difficulty predicting burst times.",
          difficulty: "Hard",
          concept: "Practicality",
        },
        {
          id: 10,
          question: "What happens in SRTF when all processes have equal remaining time?",
          options: ["Random selection", "FCFS order", "Round Robin", "System crashes"],
          correctAnswer: 1,
          explanation: "When remaining times are equal, FCFS order is typically used as a tiebreaker.",
          difficulty: "Hard",
          concept: "Tie Breaking",
        },
      ],
    },
    "priority": {
      title: "Priority Scheduling Mini-Quest Quiz",
      timeLimit: 600,
      questions: [
        {
          id: 1,
          question: "In priority scheduling, which process gets CPU first?",
          options: ["First arrival", "Shortest burst", "Highest priority", "Random"],
          correctAnswer: 2,
          explanation: "Priority scheduling selects the process with the highest priority for execution.",
          difficulty: "Easy",
          concept: "Priority Basics",
        },
        {
          id: 2,
          question: "What is the main problem with priority scheduling?",
          options: ["Low throughput", "Starvation", "Convoy effect", "High memory usage"],
          correctAnswer: 1,
          explanation: "Low priority processes can suffer from starvation if high priority processes keep arriving.",
          difficulty: "Easy",
          concept: "Starvation",
        },
        {
          id: 3,
          question: "What is aging in priority scheduling?",
          options: ["Decreasing priority over time", "Increasing priority over time", "Removing old processes", "Adding new processes"],
          correctAnswer: 1,
          explanation: "Aging gradually increases the priority of waiting processes to prevent starvation.",
          difficulty: "Medium",
          concept: "Aging",
        },
        {
          id: 4,
          question: "Can priority scheduling be preemptive?",
          options: ["No, always non-preemptive", "Yes, can be preemptive", "Only in real-time systems", "Only in batch systems"],
          correctAnswer: 1,
          explanation: "Priority scheduling can be implemented as both preemptive and non-preemptive.",
          difficulty: "Medium",
          concept: "Preemption",
        },
        {
          id: 5,
          question: "In preemptive priority scheduling, when does preemption occur?",
          options: ["Every time quantum", "When higher priority process arrives", "When process completes", "Randomly"],
          correctAnswer: 1,
          explanation: "Preemption occurs when a process with higher priority than the current process arrives.",
          difficulty: "Easy",
          concept: "Preemption Logic",
        },
        {
          id: 6,
          question: "What are the two types of priorities?",
          options: ["High and Low", "Internal and External", "Static and Dynamic", "Fast and Slow"],
          correctAnswer: 1,
          explanation: "Priorities can be internal (defined by OS based on metrics) or external (defined by user/system admin).",
          difficulty: "Hard",
          concept: "Priority Types",
        },
        {
          id: 7,
          question: "Which number typically represents highest priority?",
          options: ["Always 0", "Always 1", "Depends on system", "Always 100"],
          correctAnswer: 2,
          explanation: "Some systems use 0 as highest priority, others use larger numbers. It depends on the system convention.",
          difficulty: "Medium",
          concept: "Priority Values",
        },
        {
          id: 8,
          question: "How does priority inversion occur?",
          options: ["High priority waits for low priority", "Low priority runs first", "Priorities are swapped", "System error"],
          correctAnswer: 0,
          explanation: "Priority inversion occurs when a high priority process waits for a resource held by a low priority process.",
          difficulty: "Hard",
          concept: "Priority Inversion",
        },
        {
          id: 9,
          question: "What is priority inheritance?",
          options: ["Child inherits parent priority", "Low priority temporarily gets high priority", "Priority decreases over time", "Priority increases over time"],
          correctAnswer: 1,
          explanation: "Priority inheritance temporarily boosts a low priority process holding a resource needed by high priority process.",
          difficulty: "Hard",
          concept: "Priority Inheritance",
        },
        {
          id: 10,
          question: "Is priority scheduling suitable for real-time systems?",
          options: ["No, never", "Yes, commonly used", "Only for soft real-time", "Only for hard real-time"],
          correctAnswer: 1,
          explanation: "Priority scheduling is commonly used in real-time systems where certain tasks must execute with higher priority.",
          difficulty: "Medium",
          concept: "Real-Time Systems",
        },
      ],
    },
    "round-robin": {
      title: "Round Robin Mini-Quest Quiz",
      timeLimit: 600,
      questions: [
        {
          id: 1,
          question: "What is the key parameter in Round Robin scheduling?",
          options: ["Priority", "Burst time", "Time quantum", "Arrival time"],
          correctAnswer: 2,
          explanation: "Time quantum (or time slice) is the key parameter that determines how long each process runs.",
          difficulty: "Easy",
          concept: "Time Quantum",
        },
        {
          id: 2,
          question: "Is Round Robin preemptive or non-preemptive?",
          options: ["Non-preemptive", "Preemptive", "Both", "Neither"],
          correctAnswer: 1,
          explanation: "Round Robin is a preemptive algorithm that switches processes after each time quantum.",
          difficulty: "Easy",
          concept: "Preemption",
        },
        {
          id: 3,
          question: "What happens when a process's time quantum expires?",
          options: ["Process terminates", "Process moves to end of queue", "Process gets higher priority", "Process is blocked"],
          correctAnswer: 1,
          explanation: "When time quantum expires, the process is preempted and moved to the end of the ready queue.",
          difficulty: "Easy",
          concept: "Queue Management",
        },
        {
          id: 4,
          question: "Can Round Robin cause starvation?",
          options: ["Yes, frequently", "No, never", "Only with large quantum", "Only with small quantum"],
          correctAnswer: 1,
          explanation: "Round Robin cannot cause starvation as every process gets CPU time in a cyclic manner.",
          difficulty: "Medium",
          concept: "Starvation",
        },
        {
          id: 5,
          question: "What happens if time quantum is too large?",
          options: ["Becomes like FCFS", "Becomes like SJF", "System crashes", "Starvation occurs"],
          correctAnswer: 0,
          explanation: "If time quantum is very large, Round Robin behaves like FCFS as processes complete within one quantum.",
          difficulty: "Medium",
          concept: "Quantum Size",
        },
        {
          id: 6,
          question: "What happens if time quantum is too small?",
          options: ["Better response time", "High context switching overhead", "Lower throughput", "Both B and C"],
          correctAnswer: 3,
          explanation: "Very small time quantum causes excessive context switching, reducing throughput despite better response time.",
          difficulty: "Hard",
          concept: "Quantum Size",
        },
        {
          id: 7,
          question: "What is the typical range for time quantum?",
          options: ["1-10 microseconds", "10-100 milliseconds", "1-10 seconds", "1-10 minutes"],
          correctAnswer: 1,
          explanation: "Time quantum typically ranges from 10-100 milliseconds to balance response time and overhead.",
          difficulty: "Medium",
          concept: "Quantum Selection",
        },
        {
          id: 8,
          question: "Is Round Robin suitable for time-sharing systems?",
          options: ["No, not suitable", "Yes, ideal", "Only for batch systems", "Only for real-time systems"],
          correctAnswer: 1,
          explanation: "Round Robin is ideal for time-sharing systems as it provides fair CPU time and good response time.",
          difficulty: "Easy",
          concept: "System Suitability",
        },
        {
          id: 9,
          question: "What data structure is used to implement Round Robin?",
          options: ["Stack", "Circular queue", "Priority queue", "Binary tree"],
          correctAnswer: 1,
          explanation: "Round Robin uses a circular queue (FIFO) to maintain the ready processes.",
          difficulty: "Medium",
          concept: "Implementation",
        },
        {
          id: 10,
          question: "How does Round Robin compare to FCFS in terms of average waiting time?",
          options: ["Always better", "Always worse", "Usually better for short processes", "Same"],
          correctAnswer: 2,
          explanation: "Round Robin usually provides better average waiting time for short processes compared to FCFS.",
          difficulty: "Hard",
          concept: "Performance",
        },
      ],
    },
  },
  "memory-management": {
    "first-fit": {
      title: "First-Fit Mini-Quest Quiz",
      timeLimit: 600,
      questions: [
        {
          id: 1,
          question: "What is the First-Fit memory allocation strategy?",
          options: ["Allocate to smallest hole", "Allocate to first sufficient hole", "Allocate to largest hole", "Allocate randomly"],
          correctAnswer: 1,
          explanation: "First-Fit allocates memory to the first hole that is large enough.",
          difficulty: "Easy",
          concept: "First-Fit Basics",
        },
        {
          id: 2,
          question: "What is the main advantage of First-Fit?",
          options: ["Minimum fragmentation", "Fast allocation", "Best memory utilization", "No external fragmentation"],
          correctAnswer: 1,
          explanation: "First-Fit is fast because it stops searching as soon as it finds a suitable hole.",
          difficulty: "Easy",
          concept: "Advantages",
        },
        {
          id: 3,
          question: "Does First-Fit cause external fragmentation?",
          options: ["No, never", "Yes, can cause", "Only with large blocks", "Only with small blocks"],
          correctAnswer: 1,
          explanation: "First-Fit can cause external fragmentation as it may leave small unusable holes.",
          difficulty: "Medium",
          concept: "Fragmentation",
        },
        {
          id: 4,
          question: "What data structure is commonly used for First-Fit?",
          options: ["Array", "Linked list", "Binary tree", "Hash table"],
          correctAnswer: 1,
          explanation: "A linked list of free memory blocks is commonly used to implement First-Fit.",
          difficulty: "Medium",
          concept: "Implementation",
        },
        {
          id: 5,
          question: "What is the time complexity of First-Fit allocation?",
          options: ["O(1)", "O(n)", "O(log n)", "O(n²)"],
          correctAnswer: 1,
          explanation: "First-Fit has O(n) time complexity in worst case, where n is the number of free blocks.",
          difficulty: "Hard",
          concept: "Complexity",
        },
        {
          id: 6,
          question: "How does First-Fit compare to Best-Fit in speed?",
          options: ["Slower", "Faster", "Same speed", "Depends on memory size"],
          correctAnswer: 1,
          explanation: "First-Fit is generally faster than Best-Fit as it doesn't need to search the entire list.",
          difficulty: "Medium",
          concept: "Comparison",
        },
        {
          id: 7,
          question: "What happens to the remaining space after First-Fit allocation?",
          options: ["Discarded", "Remains as free hole", "Merged with next block", "Allocated to OS"],
          correctAnswer: 1,
          explanation: "The remaining space after allocation stays as a smaller free hole in the list.",
          difficulty: "Easy",
          concept: "Allocation Process",
        },
        {
          id: 8,
          question: "Can First-Fit lead to memory compaction?",
          options: ["No, never needed", "Yes, may be needed", "Only in virtual memory", "Only in paging"],
          correctAnswer: 1,
          explanation: "First-Fit can create fragmentation that may require memory compaction to consolidate free space.",
          difficulty: "Hard",
          concept: "Compaction",
        },
        {
          id: 9,
          question: "Where does First-Fit typically start searching?",
          options: ["End of memory", "Beginning of list", "Middle of list", "Random position"],
          correctAnswer: 1,
          explanation: "First-Fit typically starts searching from the beginning of the free block list.",
          difficulty: "Easy",
          concept: "Search Strategy",
        },
        {
          id: 10,
          question: "Is First-Fit optimal for memory utilization?",
          options: ["Yes, always optimal", "No, not optimal", "Only for sorted lists", "Only for large blocks"],
          correctAnswer: 1,
          explanation: "First-Fit is not optimal for memory utilization; it prioritizes speed over optimal placement.",
          difficulty: "Medium",
          concept: "Optimality",
        },
      ],
    },
    "best-fit": {
      title: "Best-Fit Mini-Quest Quiz",
      timeLimit: 600,
      questions: [
        { id: 1, question: "What is the Best-Fit allocation strategy?", options: ["First sufficient hole", "Smallest sufficient hole", "Largest hole", "Random hole"], correctAnswer: 1, explanation: "Best-Fit allocates to the smallest hole that is large enough.", difficulty: "Easy", concept: "Best-Fit Basics" },
        { id: 2, question: "What is the main advantage of Best-Fit?", options: ["Fastest allocation", "Minimizes wasted space", "No fragmentation", "Simple implementation"], correctAnswer: 1, explanation: "Best-Fit minimizes wasted space by choosing the smallest sufficient hole.", difficulty: "Easy", concept: "Advantages" },
        { id: 3, question: "What is the main disadvantage of Best-Fit?", options: ["High memory waste", "Slow allocation", "Causes starvation", "No external fragmentation"], correctAnswer: 1, explanation: "Best-Fit is slower as it must search the entire list to find the best hole.", difficulty: "Medium", concept: "Disadvantages" },
        { id: 4, question: "Does Best-Fit eliminate external fragmentation?", options: ["Yes, completely", "No, can still occur", "Only with compaction", "Only in paging"], correctAnswer: 1, explanation: "Best-Fit can still cause external fragmentation, often creating many small unusable holes.", difficulty: "Medium", concept: "Fragmentation" },
        { id: 5, question: "What is the time complexity of Best-Fit?", options: ["O(1)", "O(n)", "O(log n)", "O(n²)"], correctAnswer: 1, explanation: "Best-Fit has O(n) complexity as it must search all free blocks.", difficulty: "Hard", concept: "Complexity" },
        { id: 6, question: "How does Best-Fit compare to First-Fit in memory utilization?", options: ["Worse", "Better", "Same", "Depends on workload"], correctAnswer: 3, explanation: "Best-Fit can have better or worse utilization depending on the allocation pattern.", difficulty: "Hard", concept: "Comparison" },
        { id: 7, question: "What type of fragmentation does Best-Fit tend to create?", options: ["Large holes", "Many tiny holes", "No fragmentation", "Internal fragmentation"], correctAnswer: 1, explanation: "Best-Fit tends to create many tiny unusable holes.", difficulty: "Medium", concept: "Fragmentation Pattern" },
        { id: 8, question: "Can Best-Fit be optimized with sorted lists?", options: ["No benefit", "Yes, by size", "Yes, by address", "Yes, by age"], correctAnswer: 1, explanation: "Sorting free blocks by size can optimize Best-Fit search.", difficulty: "Hard", concept: "Optimization" },
        { id: 9, question: "Is Best-Fit suitable for real-time systems?", options: ["Yes, ideal", "No, too slow", "Only with optimization", "Only for small memory"], correctAnswer: 1, explanation: "Best-Fit's search overhead makes it unsuitable for real-time systems.", difficulty: "Medium", concept: "Suitability" },
        { id: 10, question: "What happens if no hole is large enough in Best-Fit?", options: ["Allocate anyway", "Allocation fails", "Create new hole", "Use swap space"], correctAnswer: 1, explanation: "If no sufficient hole exists, the allocation request fails.", difficulty: "Easy", concept: "Allocation Failure" },
      ],
    },
    "worst-fit": {
      title: "Worst-Fit Mini-Quest Quiz",
      timeLimit: 600,
      questions: [
        { id: 1, question: "What is the Worst-Fit allocation strategy?", options: ["Smallest hole", "First hole", "Largest hole", "Random hole"], correctAnswer: 2, explanation: "Worst-Fit allocates to the largest available hole.", difficulty: "Easy", concept: "Worst-Fit Basics" },
        { id: 2, question: "What is the goal of Worst-Fit?", options: ["Minimize fragmentation", "Leave large usable holes", "Fastest allocation", "Best utilization"], correctAnswer: 1, explanation: "Worst-Fit aims to leave large enough holes that can be reused.", difficulty: "Medium", concept: "Goals" },
        { id: 3, question: "How does Worst-Fit perform compared to First-Fit?", options: ["Always better", "Always worse", "Similar performance", "Depends on workload"], correctAnswer: 3, explanation: "Worst-Fit performance varies depending on the allocation pattern.", difficulty: "Hard", concept: "Performance" },
        { id: 4, question: "What is the time complexity of Worst-Fit?", options: ["O(1)", "O(n)", "O(log n)", "O(n²)"], correctAnswer: 1, explanation: "Worst-Fit has O(n) complexity as it must find the largest hole.", difficulty: "Medium", concept: "Complexity" },
        { id: 5, question: "Can Worst-Fit be optimized?", options: ["No optimization possible", "Yes, with sorted list", "Yes, with hash table", "Yes, with binary tree"], correctAnswer: 1, explanation: "Maintaining a sorted list by size can optimize Worst-Fit.", difficulty: "Hard", concept: "Optimization" },
        { id: 6, question: "Does Worst-Fit eliminate fragmentation?", options: ["Yes, completely", "No, still occurs", "Only external", "Only internal"], correctAnswer: 1, explanation: "Worst-Fit can still cause fragmentation, though patterns differ from other algorithms.", difficulty: "Medium", concept: "Fragmentation" },
        { id: 7, question: "Is Worst-Fit commonly used in practice?", options: ["Yes, very common", "No, rarely used", "Only in embedded systems", "Only in mainframes"], correctAnswer: 1, explanation: "Worst-Fit is rarely used in practice due to poor performance.", difficulty: "Easy", concept: "Practical Use" },
        { id: 8, question: "What type of holes does Worst-Fit tend to create?", options: ["Many small holes", "Few large holes", "No holes", "Equal-sized holes"], correctAnswer: 0, explanation: "Worst-Fit tends to break up large holes, creating many smaller ones.", difficulty: "Medium", concept: "Fragmentation Pattern" },
        { id: 9, question: "How does Worst-Fit compare to Best-Fit in speed?", options: ["Faster", "Slower", "Same speed", "Depends on implementation"], correctAnswer: 2, explanation: "Both require searching the entire list, so they have similar speed.", difficulty: "Hard", concept: "Comparison" },
        { id: 10, question: "When might Worst-Fit be preferred?", options: ["Never", "When large allocations are common", "When small allocations are common", "In real-time systems"], correctAnswer: 1, explanation: "Worst-Fit might be preferred when large allocations are common and need large holes.", difficulty: "Hard", concept: "Use Cases" },
      ],
    },
    "paging": {
      title: "Paging Mini-Quest Quiz",
      timeLimit: 720,
      questions: [
        { id: 1, question: "What is paging in memory management?", options: ["Variable-size allocation", "Fixed-size pages and frames", "Only cache mapping", "Disk-only management"], correctAnswer: 1, explanation: "Paging divides logical memory into fixed-size pages and physical memory into fixed-size frames.", difficulty: "Easy", concept: "Paging Basics" },
        { id: 2, question: "What maps pages to frames?", options: ["Segment table", "Page table", "Inode table", "Ready queue"], correctAnswer: 1, explanation: "A page table stores the mapping from virtual pages to physical frames.", difficulty: "Easy", concept: "Page Table" },
        { id: 3, question: "What is a page fault?", options: ["CPU overheat", "Missing page in memory", "Invalid process state", "Cache write-back"], correctAnswer: 1, explanation: "A page fault occurs when the referenced page is not currently in physical memory.", difficulty: "Medium", concept: "Page Faults" },
        { id: 4, question: "Paging primarily removes which fragmentation type?", options: ["Internal", "External", "Both", "None"], correctAnswer: 1, explanation: "Paging eliminates external fragmentation because any free frame can store a page.", difficulty: "Medium", concept: "Fragmentation" },
        { id: 5, question: "Which issue can still occur with paging?", options: ["No memory waste", "Internal fragmentation", "Only deadlock", "Only starvation"], correctAnswer: 1, explanation: "Internal fragmentation may occur in the last page of a process.", difficulty: "Medium", concept: "Internal Fragmentation" },
        { id: 6, question: "What is the role of the TLB?", options: ["Store process code", "Cache page table entries", "Schedule processes", "Encrypt memory"], correctAnswer: 1, explanation: "The Translation Lookaside Buffer caches recent page-table mappings for faster translation.", difficulty: "Hard", concept: "TLB" },
        { id: 7, question: "Effective access time improves when TLB hit ratio is:", options: ["Low", "Zero", "High", "Negative"], correctAnswer: 2, explanation: "A higher TLB hit ratio reduces average address translation overhead.", difficulty: "Hard", concept: "Performance" },
        { id: 8, question: "When memory is full and a new page is needed, OS performs:", options: ["Thread merge", "Page replacement", "Context freeze", "Priority aging"], correctAnswer: 1, explanation: "Page replacement selects a victim page to evict and load the required page.", difficulty: "Medium", concept: "Replacement" },
        { id: 9, question: "Which page replacement algorithm can suffer Belady's anomaly?", options: ["Optimal", "FIFO", "LRU", "Clock"], correctAnswer: 1, explanation: "FIFO can show Belady's anomaly where more frames lead to more faults.", difficulty: "Hard", concept: "Belady Anomaly" },
        { id: 10, question: "Virtual memory with paging allows:", options: ["Only one process", "Programs larger than RAM", "No page faults", "No disk usage"], correctAnswer: 1, explanation: "Virtual memory allows execution of processes larger than physical memory by paging to disk.", difficulty: "Medium", concept: "Virtual Memory" },
      ],
    },
    "segmentation": {
      title: "Segmentation Mini-Quest Quiz",
      timeLimit: 720,
      questions: [
        { id: 1, question: "How does segmentation divide a program?", options: ["Equal-size blocks", "Logical variable-size segments", "Only by pages", "Only by files"], correctAnswer: 1, explanation: "Segmentation divides memory according to logical units like code, data, and stack.", difficulty: "Easy", concept: "Segmentation Basics" },
        { id: 2, question: "A logical address in segmentation is usually:", options: ["Frame + offset", "Segment number + offset", "Page + frame", "Block + queue"], correctAnswer: 1, explanation: "Logical addresses are represented as <segment number, offset>.", difficulty: "Easy", concept: "Address Format" },
        { id: 3, question: "What does each segment-table entry contain?", options: ["Only process ID", "Base and limit", "Only frame number", "Priority only"], correctAnswer: 1, explanation: "Segment table entries store base (start) and limit (length) for each segment.", difficulty: "Medium", concept: "Segment Table" },
        { id: 4, question: "A segmentation fault happens when:", options: ["Offset exceeds segment limit", "CPU is idle", "Two pages merge", "TLB hit occurs"], correctAnswer: 0, explanation: "If offset is outside the segment limit, access is invalid and causes a segmentation fault.", difficulty: "Medium", concept: "Segmentation Fault" },
        { id: 5, question: "Compared to paging, segmentation better supports:", options: ["Uniform frame allocation", "Program logical structure", "No protection", "No sharing"], correctAnswer: 1, explanation: "Segmentation matches programmer-visible logical units and supports per-segment protection/sharing.", difficulty: "Medium", concept: "Design Tradeoff" },
        { id: 6, question: "Segmentation mainly suffers from:", options: ["No faults", "External fragmentation", "Only internal fragmentation", "No allocation issues"], correctAnswer: 1, explanation: "Variable-size allocation in segmentation can lead to external fragmentation.", difficulty: "Medium", concept: "Fragmentation" },
        { id: 7, question: "Which mechanism can reduce segmentation fragmentation over time?", options: ["Compaction", "Round Robin", "Spooling", "Aging"], correctAnswer: 0, explanation: "Compaction relocates segments to combine free holes.", difficulty: "Hard", concept: "Compaction" },
        { id: 8, question: "Why is segment-level protection useful?", options: ["No reason", "Different access rights per segment", "Faster clocks", "Fewer processes"], correctAnswer: 1, explanation: "Code can be read-only while data may be read-write using per-segment permissions.", difficulty: "Hard", concept: "Protection" },
        { id: 9, question: "Segment sharing enables:", options: ["Duplicate code in each process", "Common code segment across processes", "Only kernel threads", "No memory savings"], correctAnswer: 1, explanation: "Processes can share a read-only code segment to save memory.", difficulty: "Hard", concept: "Sharing" },
        { id: 10, question: "The best statement about segmentation is:", options: ["Always better than paging", "Great for logical view but may fragment", "No hardware support needed", "Cannot protect memory"], correctAnswer: 1, explanation: "Segmentation models program structure well but introduces external fragmentation concerns.", difficulty: "Medium", concept: "Summary" },
      ],
    },
    "fragmentation": {
      title: "Fragmentation Mini-Quest Quiz",
      timeLimit: 720,
      questions: [
        { id: 1, question: "What is internal fragmentation?", options: ["Free space between allocations", "Unused space inside allocated block", "Disk head delay", "CPU idle time"], correctAnswer: 1, explanation: "Internal fragmentation is wasted memory inside allocated regions due to allocation granularity.", difficulty: "Easy", concept: "Internal Fragmentation" },
        { id: 2, question: "What is external fragmentation?", options: ["Unused bytes in block", "Free memory split into small noncontiguous holes", "TLB miss", "Page table overflow"], correctAnswer: 1, explanation: "External fragmentation occurs when total free memory is enough but not contiguous for a request.", difficulty: "Easy", concept: "External Fragmentation" },
        { id: 3, question: "Which method directly tackles external fragmentation?", options: ["Compaction", "FIFO scheduling", "Spooling", "Caching"], correctAnswer: 0, explanation: "Compaction merges holes by moving allocated blocks to create large contiguous free space.", difficulty: "Medium", concept: "Compaction" },
        { id: 4, question: "Paging reduces external fragmentation because:", options: ["Needs contiguous memory", "Uses fixed-size frames", "Avoids page tables", "Uses one segment"], correctAnswer: 1, explanation: "Fixed-size frames let any free frame hold a page, removing contiguous-allocation dependency.", difficulty: "Medium", concept: "Paging Benefit" },
        { id: 5, question: "Which allocation strategy often creates many tiny holes?", options: ["Best-Fit", "Round Robin", "SRTF", "Mutex"], correctAnswer: 0, explanation: "Best-Fit can leave very small leftovers that are hard to reuse.", difficulty: "Medium", concept: "Allocation Effects" },
        { id: 6, question: "A key cost of compaction is:", options: ["No overhead", "Data movement overhead", "Loss of protection", "No relocation needed"], correctAnswer: 1, explanation: "Compaction requires relocating processes/segments, which is expensive.", difficulty: "Hard", concept: "Compaction Cost" },
        { id: 7, question: "Buddy allocator mainly helps by:", options: ["Increasing starvation", "Fast split/merge of power-of-two blocks", "Removing all waste", "Eliminating page faults"], correctAnswer: 1, explanation: "Buddy systems allow efficient splitting and coalescing of blocks.", difficulty: "Hard", concept: "Buddy Allocation" },
        { id: 8, question: "Coalescing free blocks means:", options: ["Splitting free blocks", "Merging adjacent free blocks", "Locking memory", "Swapping pages"], correctAnswer: 1, explanation: "Coalescing combines neighboring free blocks into larger holes.", difficulty: "Medium", concept: "Coalescing" },
        { id: 9, question: "Which is true about internal vs external fragmentation?", options: ["Both happen only in paging", "Internal is inside blocks; external is between blocks", "Both are identical", "Neither wastes memory"], correctAnswer: 1, explanation: "Internal waste is within allocated units; external waste is scattered between allocations.", difficulty: "Easy", concept: "Comparison" },
        { id: 10, question: "An OS design choice to reduce fragmentation risk is:", options: ["Never freeing memory", "Choosing suitable allocation policy for workload", "Disabling virtual memory", "Using one process only"], correctAnswer: 1, explanation: "Allocation policies should be selected based on workload patterns to limit fragmentation.", difficulty: "Medium", concept: "Policy Design" },
      ],
    },
  },
  "process-synchronization": {
    "critical-section": {
      title: "Critical Section Mini-Quest Quiz",
      timeLimit: 600,
      questions: [
        { id: 1, question: "What is a critical section?", options: ["Code that runs fast", "Code accessing shared resources", "Code with errors", "Code in kernel"], correctAnswer: 1, explanation: "A critical section is code that accesses shared resources and must not be executed by multiple processes simultaneously.", difficulty: "Easy", concept: "Critical Section Basics" },
        { id: 2, question: "What is mutual exclusion?", options: ["All processes run together", "Only one process in critical section", "Processes never run", "Processes run in order"], correctAnswer: 1, explanation: "Mutual exclusion ensures only one process can execute in the critical section at a time.", difficulty: "Easy", concept: "Mutual Exclusion" },
        { id: 3, question: "What is the progress requirement?", options: ["Processes must make progress", "Only waiting processes decide next entry", "All processes must wait", "Processes run forever"], correctAnswer: 1, explanation: "Progress requirement states that only processes not in remainder section can decide who enters critical section next.", difficulty: "Medium", concept: "Progress" },
        { id: 4, question: "What is bounded waiting?", options: ["Infinite wait time", "Limited wait time before entry", "No waiting allowed", "Random wait time"], correctAnswer: 1, explanation: "Bounded waiting ensures a process will enter critical section after a finite number of other processes.", difficulty: "Medium", concept: "Bounded Waiting" },
        { id: 5, question: "What is a race condition?", options: ["Processes racing to finish", "Outcome depends on execution order", "Processes running in parallel", "Deadlock situation"], correctAnswer: 1, explanation: "A race condition occurs when the outcome depends on the non-deterministic ordering of process execution.", difficulty: "Easy", concept: "Race Condition" },
        { id: 6, question: "Can busy waiting be a problem?", options: ["No, it's efficient", "Yes, wastes CPU cycles", "Only in single-core systems", "Only in multi-core systems"], correctAnswer: 1, explanation: "Busy waiting wastes CPU cycles as the process continuously checks a condition.", difficulty: "Medium", concept: "Busy Waiting" },
        { id: 7, question: "What is a lock variable?", options: ["Variable that never changes", "Variable controlling critical section access", "Variable in memory", "Variable in register"], correctAnswer: 1, explanation: "A lock variable is used to control access to the critical section.", difficulty: "Easy", concept: "Lock Variable" },
        { id: 8, question: "Are hardware instructions needed for synchronization?", options: ["No, software is enough", "Yes, atomic instructions help", "Only in embedded systems", "Only in supercomputers"], correctAnswer: 1, explanation: "Atomic hardware instructions like Test-and-Set help implement synchronization correctly.", difficulty: "Hard", concept: "Hardware Support" },
        { id: 9, question: "What is the entry section?", options: ["Code before critical section", "Code requesting permission to enter", "Code after critical section", "Code in critical section"], correctAnswer: 1, explanation: "Entry section is code that requests permission to enter the critical section.", difficulty: "Easy", concept: "Entry Section" },
        { id: 10, question: "What is the exit section?", options: ["Code to terminate process", "Code to release critical section", "Code before entry", "Code in critical section"], correctAnswer: 1, explanation: "Exit section releases the critical section so other processes can enter.", difficulty: "Easy", concept: "Exit Section" },
      ],
    },
    "mutex": {
      title: "Mutex Mini-Quest Quiz",
      timeLimit: 600,
      questions: [
        { id: 1, question: "What is a mutex primarily used for?", options: ["CPU scheduling", "Mutual exclusion", "Memory paging", "Deadlock detection only"], correctAnswer: 1, explanation: "A mutex ensures only one thread/process enters a critical section at a time.", difficulty: "Easy", concept: "Mutex Basics" },
        { id: 2, question: "A mutex usually has states:", options: ["Open/Close", "Locked/Unlocked", "Ready/Blocked", "On/Off/Wait"], correctAnswer: 1, explanation: "Mutex lock state is typically locked or unlocked.", difficulty: "Easy", concept: "State" },
        { id: 3, question: "What happens if a thread tries to lock an already locked mutex?", options: ["Always crashes", "It waits/blocks", "It gets priority boost automatically", "Mutex is destroyed"], correctAnswer: 1, explanation: "The thread generally blocks (or spins, depending on implementation) until the mutex is released.", difficulty: "Medium", concept: "Lock Behavior" },
        { id: 4, question: "Why should the same thread unlock the mutex it locked?", options: ["No reason", "Ownership semantics", "To increase page hits", "To avoid context switch"], correctAnswer: 1, explanation: "Mutexes typically enforce ownership to prevent incorrect unlock behavior.", difficulty: "Medium", concept: "Ownership" },
        { id: 5, question: "Which bug can happen if a mutex is never unlocked?", options: ["Race condition only", "Deadlock/blocking", "Cache miss", "Page fault"], correctAnswer: 1, explanation: "Failing to unlock can cause other threads to block indefinitely.", difficulty: "Easy", concept: "Deadlock Risk" },
        { id: 6, question: "Priority inversion with mutex occurs when:", options: ["High-priority thread waits on low-priority holder", "Low waits on high", "All threads same priority", "No lock exists"], correctAnswer: 0, explanation: "A high-priority task can be blocked by a low-priority task holding the mutex.", difficulty: "Hard", concept: "Priority Inversion" },
        { id: 7, question: "A common mitigation for priority inversion is:", options: ["Round Robin", "Priority inheritance", "Compaction", "Paging"], correctAnswer: 1, explanation: "Priority inheritance temporarily raises the lock holder's priority.", difficulty: "Hard", concept: "Mitigation" },
        { id: 8, question: "Nested locking without fixed order can lead to:", options: ["Starvation only", "Deadlock", "No issues", "Faster execution"], correctAnswer: 1, explanation: "Inconsistent lock acquisition order is a common source of deadlock.", difficulty: "Medium", concept: "Lock Ordering" },
        { id: 9, question: "Difference between mutex and binary semaphore:", options: ["No difference", "Mutex has ownership; binary semaphore often does not", "Semaphore is always faster", "Mutex counts resources"], correctAnswer: 1, explanation: "Mutexes are ownership-based locks, unlike many binary semaphore usages.", difficulty: "Hard", concept: "Comparison" },
        { id: 10, question: "Best practice with mutex in critical path code:", options: ["Lock for long time", "Keep critical section short", "Lock unrelated resources", "Ignore contention"], correctAnswer: 1, explanation: "Short critical sections reduce contention and improve concurrency.", difficulty: "Easy", concept: "Best Practices" },
      ],
    },
    "binary-semaphore": {
      title: "Binary Semaphore Mini-Quest Quiz",
      timeLimit: 600,
      questions: [
        { id: 1, question: "A binary semaphore value can be:", options: ["Any integer", "0 or 1", "-1 or 1", "Only 1"], correctAnswer: 1, explanation: "Binary semaphores are limited to two states represented by 0 and 1.", difficulty: "Easy", concept: "Binary Basics" },
        { id: 2, question: "Which operations are used with semaphores?", options: ["open/close", "wait/signal", "push/pop", "read/write"], correctAnswer: 1, explanation: "Semaphore synchronization is based on wait and signal operations.", difficulty: "Easy", concept: "Operations" },
        { id: 3, question: "Binary semaphore is commonly used for:", options: ["Counting many resources", "Mutual exclusion or event signaling", "Page translation", "CPU burst prediction"], correctAnswer: 1, explanation: "It is suitable for single resource access or synchronization events.", difficulty: "Medium", concept: "Use Cases" },
        { id: 4, question: "How does binary semaphore differ from counting semaphore?", options: ["No difference", "Binary is limited to 0/1", "Binary allows unlimited count", "Counting has no atomic ops"], correctAnswer: 1, explanation: "Counting semaphores track multiple resources, binary semaphores only two states.", difficulty: "Easy", concept: "Comparison" },
        { id: 5, question: "If wait() is called when value is 0, process will:", options: ["Proceed immediately", "Block until signal", "Reset semaphore", "Crash"], correctAnswer: 1, explanation: "At 0, no permit is available, so the caller waits.", difficulty: "Medium", concept: "Blocking" },
        { id: 6, question: "Signal() on a binary semaphore typically:", options: ["Decrements value", "Releases permit/wakes waiter", "Deletes semaphore", "Changes priority"], correctAnswer: 1, explanation: "Signal releases the semaphore and may wake a blocked process.", difficulty: "Medium", concept: "Release" },
        { id: 7, question: "Can misuse of binary semaphores cause deadlocks?", options: ["No", "Yes", "Only in paging", "Only in single-threaded apps"], correctAnswer: 1, explanation: "Incorrect wait/signal ordering can still deadlock.", difficulty: "Medium", concept: "Deadlock" },
        { id: 8, question: "A binary semaphore used for one-time event notification acts like:", options: ["Queue", "Signal flag", "Page table", "Timer interrupt"], correctAnswer: 1, explanation: "It can synchronize producer/consumer style events as a signal.", difficulty: "Hard", concept: "Event Sync" },
        { id: 9, question: "Which statement is true about fairness?", options: ["Binary semaphores always fair", "Fairness depends on implementation/policy", "Fairness impossible", "Fairness only with paging"], correctAnswer: 1, explanation: "Wake-up ordering is OS/runtime dependent unless fairness policy is enforced.", difficulty: "Hard", concept: "Fairness" },
        { id: 10, question: "For strict lock ownership, which is usually preferred?", options: ["Binary semaphore", "Mutex", "Condition variable", "Spinlock always"], correctAnswer: 1, explanation: "Mutexes are generally preferred where lock ownership semantics matter.", difficulty: "Medium", concept: "Primitive Choice" },
      ],
    },
    "counting-semaphore": {
      title: "Counting Semaphore Mini-Quest Quiz",
      timeLimit: 600,
      questions: [
        { id: 1, question: "What is a counting semaphore?", options: ["Binary variable", "Integer variable for resource counting", "Boolean flag", "Lock variable"], correctAnswer: 1, explanation: "A counting semaphore is an integer variable used to count available resources.", difficulty: "Easy", concept: "Semaphore Basics" },
        { id: 2, question: "What are the two atomic operations on semaphores?", options: ["Lock and Unlock", "Wait and Signal", "Get and Put", "Acquire and Release"], correctAnswer: 1, explanation: "Wait (P) and Signal (V) are the two atomic operations on semaphores.", difficulty: "Easy", concept: "Semaphore Operations" },
        { id: 3, question: "What does the wait() operation do?", options: ["Increments semaphore", "Decrements semaphore", "Resets semaphore", "Checks semaphore"], correctAnswer: 1, explanation: "Wait() decrements the semaphore value and blocks if the value becomes negative.", difficulty: "Medium", concept: "Wait Operation" },
        { id: 4, question: "What does the signal() operation do?", options: ["Decrements semaphore", "Increments semaphore", "Resets semaphore", "Destroys semaphore"], correctAnswer: 1, explanation: "Signal() increments the semaphore value and may wake up a waiting process.", difficulty: "Medium", concept: "Signal Operation" },
        { id: 5, question: "What is the initial value of a counting semaphore?", options: ["Always 0", "Always 1", "Number of available resources", "Infinity"], correctAnswer: 2, explanation: "The initial value equals the number of available resources.", difficulty: "Easy", concept: "Initialization" },
        { id: 6, question: "Can a counting semaphore be negative?", options: ["No, never", "Yes, indicates waiting processes", "Only in error conditions", "Only in binary semaphores"], correctAnswer: 1, explanation: "A negative value indicates the number of processes waiting for the resource.", difficulty: "Hard", concept: "Negative Values" },
        { id: 7, question: "How does counting semaphore differ from binary semaphore?", options: ["No difference", "Can have values > 1", "Faster execution", "Uses less memory"], correctAnswer: 1, explanation: "Counting semaphores can have values greater than 1, while binary semaphores are limited to 0 and 1.", difficulty: "Medium", concept: "Comparison" },
        { id: 8, question: "Are semaphore operations atomic?", options: ["No, can be interrupted", "Yes, must be atomic", "Only wait() is atomic", "Only signal() is atomic"], correctAnswer: 1, explanation: "Both wait() and signal() must be atomic operations to prevent race conditions.", difficulty: "Medium", concept: "Atomicity" },
        { id: 9, question: "Can semaphores solve the critical section problem?", options: ["No, cannot solve", "Yes, can solve", "Only with mutex", "Only with monitors"], correctAnswer: 1, explanation: "Semaphores can effectively solve the critical section problem.", difficulty: "Easy", concept: "Problem Solving" },
        { id: 10, question: "What is a common use of counting semaphores?", options: ["Mutual exclusion only", "Resource pool management", "Memory allocation", "Process scheduling"], correctAnswer: 1, explanation: "Counting semaphores are commonly used to manage pools of identical resources.", difficulty: "Medium", concept: "Use Cases" },
      ],
    },
    "producer-consumer": {
      title: "Producer-Consumer Mini-Quest Quiz",
      timeLimit: 600,
      questions: [
        { id: 1, question: "What is the producer-consumer problem?", options: ["Memory allocation issue", "Synchronization problem with shared buffer", "Scheduling problem", "Deadlock scenario"], correctAnswer: 1, explanation: "The producer-consumer problem involves synchronizing access to a shared buffer between producers and consumers.", difficulty: "Easy", concept: "Problem Definition" },
        { id: 2, question: "What does the producer do?", options: ["Consumes items", "Produces items and adds to buffer", "Manages buffer", "Schedules processes"], correctAnswer: 1, explanation: "The producer creates items and adds them to the shared buffer.", difficulty: "Easy", concept: "Producer Role" },
        { id: 3, question: "What does the consumer do?", options: ["Produces items", "Removes items from buffer", "Creates buffer", "Destroys buffer"], correctAnswer: 1, explanation: "The consumer removes items from the shared buffer for processing.", difficulty: "Easy", concept: "Consumer Role" },
        { id: 4, question: "What happens when the buffer is full?", options: ["Producer continues", "Producer must wait", "Consumer waits", "System crashes"], correctAnswer: 1, explanation: "When the buffer is full, the producer must wait until space becomes available.", difficulty: "Medium", concept: "Buffer Full" },
        { id: 5, question: "What happens when the buffer is empty?", options: ["Consumer continues", "Producer waits", "Consumer must wait", "Buffer is deleted"], correctAnswer: 2, explanation: "When the buffer is empty, the consumer must wait until items are available.", difficulty: "Medium", concept: "Buffer Empty" },
        { id: 6, question: "How many semaphores are typically needed?", options: ["One", "Two", "Three", "Four"], correctAnswer: 2, explanation: "Three semaphores are typically needed: empty, full, and mutex for buffer access.", difficulty: "Hard", concept: "Semaphore Count" },
        { id: 7, question: "What is the purpose of the 'empty' semaphore?", options: ["Counts full slots", "Counts empty slots", "Provides mutual exclusion", "Signals completion"], correctAnswer: 1, explanation: "The 'empty' semaphore counts the number of empty slots in the buffer.", difficulty: "Medium", concept: "Empty Semaphore" },
        { id: 8, question: "What is the purpose of the 'full' semaphore?", options: ["Counts empty slots", "Counts full slots", "Provides mutual exclusion", "Signals errors"], correctAnswer: 1, explanation: "The 'full' semaphore counts the number of full slots in the buffer.", difficulty: "Medium", concept: "Full Semaphore" },
        { id: 9, question: "Why is a mutex needed in addition to empty/full semaphores?", options: ["Not needed", "To protect buffer access", "To count items", "To signal completion"], correctAnswer: 1, explanation: "A mutex is needed to ensure mutual exclusion when accessing the buffer structure.", difficulty: "Hard", concept: "Mutex Need" },
        { id: 10, question: "Can multiple producers and consumers exist?", options: ["No, only one each", "Yes, multiple of each", "Only multiple producers", "Only multiple consumers"], correctAnswer: 1, explanation: "The solution supports multiple producers and consumers accessing the shared buffer.", difficulty: "Medium", concept: "Multiple Processes" },
      ],
    },
    "dining-philosophers": {
      title: "Dining Philosophers Mini-Quest Quiz",
      timeLimit: 600,
      questions: [
        { id: 1, question: "How many philosophers are in the classic problem?", options: ["Three", "Four", "Five", "Six"], correctAnswer: 2, explanation: "The classic dining philosophers problem involves five philosophers.", difficulty: "Easy", concept: "Problem Setup" },
        { id: 2, question: "What do philosophers need to eat?", options: ["One fork", "Two forks", "Three forks", "No forks"], correctAnswer: 1, explanation: "Each philosopher needs two forks (left and right) to eat.", difficulty: "Easy", concept: "Resource Requirements" },
        { id: 3, question: "What is the main problem to solve?", options: ["Starvation", "Deadlock", "Both A and B", "Race conditions"], correctAnswer: 2, explanation: "The problem must prevent both deadlock and starvation.", difficulty: "Medium", concept: "Problem Goals" },
        { id: 4, question: "When can deadlock occur?", options: ["Never", "When all pick up left fork simultaneously", "When all are thinking", "When all are eating"], correctAnswer: 1, explanation: "Deadlock occurs if all philosophers pick up their left fork simultaneously and wait for the right fork.", difficulty: "Medium", concept: "Deadlock Condition" },
        { id: 5, question: "What is one solution to prevent deadlock?", options: ["Allow only 4 to eat", "Pick up both forks atomically", "Use asymmetric solution", "All of the above"], correctAnswer: 3, explanation: "Multiple solutions exist: limiting concurrent eaters, atomic fork pickup, or asymmetric fork ordering.", difficulty: "Hard", concept: "Solutions" },
        { id: 6, question: "What is the asymmetric solution?", options: ["All pick left first", "Odd pick left, even pick right first", "Random order", "No solution"], correctAnswer: 1, explanation: "In the asymmetric solution, odd-numbered philosophers pick left first, even-numbered pick right first.", difficulty: "Hard", concept: "Asymmetric Solution" },
        { id: 7, question: "Can semaphores solve this problem?", options: ["No, impossible", "Yes, with proper design", "Only with monitors", "Only with mutex"], correctAnswer: 1, explanation: "Semaphores can solve the dining philosophers problem with proper design.", difficulty: "Medium", concept: "Semaphore Solution" },
        { id: 8, question: "What represents the forks in implementation?", options: ["Integers", "Semaphores or mutexes", "Boolean flags", "Pointers"], correctAnswer: 1, explanation: "Forks are typically represented as semaphores or mutexes.", difficulty: "Easy", concept: "Implementation" },
        { id: 9, question: "What are the three states of a philosopher?", options: ["Eating, Sleeping, Working", "Thinking, Hungry, Eating", "Waiting, Running, Blocked", "Active, Idle, Dead"], correctAnswer: 1, explanation: "The three states are: thinking, hungry (waiting for forks), and eating.", difficulty: "Easy", concept: "Philosopher States" },
        { id: 10, question: "Is the dining philosophers problem practical?", options: ["No, just theoretical", "Yes, models resource allocation", "Only for databases", "Only for networks"], correctAnswer: 1, explanation: "The problem models real-world resource allocation scenarios in concurrent systems.", difficulty: "Medium", concept: "Practical Relevance" },
      ],
    },
  },
};
